#!/bin/sh
# Vim translation helper
# Author: Jaeho Shin <netj@sparcs.org>
# Created: 2007-04-17

here=`dirname "$0"`
for f in "$@"; do
    (
    cd "$here"
    vim +1 doc/$f.kox \
        +"set fenc=utf-8 | set fencs=ucs-bom,utf-8,korea" \
        +"set listchars=tab:>.,eol:$" \
        +"set list" \
        +"new +1 \$VIMRUNTIME/doc/$f.txt" \
        +"set scrollbind" \
        +"norm w" \
        +"set scrollbind|norm \`\"" \

    )
done
